name = "example-jboss"
description = "An example jboss server"
version = "0.0.1"

[[packages]]
name = "jboss-servlet-3.1-api"
version = "*"

[[packages]]
name = "jboss-interceptors-1.2-api"
version = "*"

[[packages]]
name = "java-1.8.0-openjdk"
version = "*"
